version: "3"
services: 
  api: # サービスの名前(プレフィックスにディレクトリ名が入る)
    build:
      context: .
    tty: true
    ports:
      - 1323:1323
    volumes:
      - .:/go/src/api
    depends_on:
      - redis
  redis:
    image: redis:6.2.6