version: "3.4"
services: 
  app: # サービスの名前(プレフィックスにディレクトリ名が入る)
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: base
    # tty: true
    # docker-composeで指定するcommandはDockerfileよりも優先される
    command: "air -c .air.toml"
    ports:
      - 1323:1323
    volumes:
      # 現在のディレクトリをマウントする
       - .:/app/go/base
    depends_on:
      - redis
  redis:
    image: redis:6.2.6